### PR TITLE
Full App Rewrite

### PR DESCRIPTION
**Pull request by RedHawk989**
- New GUI
- Auto Update Check
- Settings Pages
- Smaller Build Size
- Installer
- Full Calibration
- Neutral Pose Calibration
- FPS Counter
- Latency Counter
- ESP Serial Support
- Save Calibration Config 
- Auto Create Config File
- OSC Receive Function for Recalibration
- Dev Credits
- and more!

### CODE REVIEW

**Comment by RamesTheGeneric** [comment]
🔥

**Review by SummerSigh — APPROVED** [review]
yeah!

**Comment by RedHawk989** [comment]
fixed merge conflicts, it's ready now

**Comment by SummerSigh** [comment]
yeaaahhhhh!

**Pull request merged**
